CONFIG_BIOMETRICS=y
CONFIG_BIOMETRICS_LOG_LEVEL_INF=y

CONFIG_TIMING_FUNCTIONS=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_MAIN_STACK_SIZE=2048

# Set to y to run legacy busy-wait baseline, n for BASE mode
CONFIG_TEST_LEGACY_BLOCKING=n

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=n